server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://112.124.46.193:4001/grade_protection?useUnicode=true&characterEncoding=UTF-8&serverTimeZone=Asia/Shanghai
    username: root
    password: 3306
    driver-class-name: com.mysql.jdbc.Driver
