server:
  port: 8081
  servlet:
    context-path: /api/v1
spring:
  datasource:
    url: jdbc:mysql://112.124.46.193:4001/grade_protection?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimeZone=Asia/Shanghai
    username: root
    password: 3306
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.das.entity